coresite/core/urls.py
from django.urls import path
from . import  views

app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('add/', views.AddView.as_view(), name='add'),
    path('posts/', views.PostsView.as_view(), name='posts'),
    path('posts/<slug:slug>/', views.SingleView.as_view(), name='single'),
    path('edit/<int:pk>/', views.EditView.as_view(), name='edit'),
    path('delete/<int:pk>/', views.DeleteView.as_view(), name='delete'),
]

coresite/coresite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/clearcache', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
]

coresite/core/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify


# Create your models here.
class Core(models.Model):
    title = models.CharField(max_length=200)
    excerpt = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='core')
    slug = models.SlugField(max_length=100, unique=True, editable=False)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)

    def get_absolute_urls(self):
        return reverse('core:single', kwargs={'slug': self.slug})
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super().save(*args, **kwargs)
    
    class Meta:
        ordering = ['-published']

coresite/core/forms.py
from django import forms
from .models import Core

class PostForm(forms.ModelForm):
    class Meta:
        model = Core
        fields = '__all__'
        # or: exclude = ['slug']

coresite/core/views.py
from django.shortcuts import render

from .models import Core
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

# Create your views here.

class IndexView(ListView):
    model = Core
    template_name = 'core/index.html'
    context_object_name = 'index'

class SingleView(DetailView):
    model = Core
    template_name = 'core/single.html'
    context_object_name = 'post'

class PostsView(ListView):
    model = Core
    template_name = 'core/posts.html'
    context_object_name = 'post_list'

class AddView(CreateView):
    '''Basically a form. Someone types in and add new post'''
    model = Core
    template_name = 'core/add.html'
    fields = '__all__' #take all the fields from the db and put that into a form
    success_url = reverse_lazy('core:posts')

class EditView(UpdateView):
    model = Core
    template_name = 'core/edit.html'
    fields = '__all__'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')

class DeleteView(DeleteView):
    model = Core 
    template_name = 'core/confirm-delete.html'
    pk_url_kwarg = 'pk'
    success_url = reverse_lazy('core:posts')
    

coresite/core/templates/core/add.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container pt-5">
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-ok"></span>Edit
            </button>
            <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

coresite/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <title>CRUD App</title>
</head>
<body>
    {% include 'core/navbar.html' %}

    {% block content %}

    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% include 'core/footer.html' %}
</body>
</html>

coresite/core/templates/core/confirm-delete.html
{% extends 'core/base.html' %}

{% block content %}

<div class="container pt-5">
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm">
    </form>
</div>

{% endblock %}

coresite/core/templates/core/edit.html
{% extends 'core/base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container pt-5">
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form.visible_fields %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
        </div>
        {% endfor %}
        <div class="form-group">
            <button type="submit" class="btn btn-success">
            <span class="glyphicon glyphicon-ok"></span>Edit
            </button>
            <a href="{% url 'core:posts' %}" class="btn btn-default">Cancel</a>
        </div>
    </form>
</div>
{% endblock %}

coresite/core/templates/core/footer.html
{% block content %}

<footer class="footer">
    <div class="container">
      <span class="text-muted">Place sticky footer content here.</span>
    </div>
</footer>

{% endblock%}

coresite/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">  
        <div class="row">
            {% for core in index %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img src="https://source.unsplash.com/random/800x600" alt="card image cap" class="card-img-top">
                        <div class="card-body">
                            <h4><a href="{{ core.get_absolute_urls }}">{{ core.title }}</a></h4>
                            <p class="card-text"></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="">
                                    <small class="text-muted">9 mins</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

coresite/core/templates/core/navbar.html
{% block content %}

<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <!-- Brand -->
    <a class="navbar-brand" href="/">Home</a>
  
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'core:posts' %}">Manage Posts</a>
          <a class="nav-link" href="{% url 'core:add' %}">Add new</a>
        </li>
      </ul>
    </div>
  </nav>
  
{% endblock%}

coresite/core/templates/core/posts.html
{% extends 'core/base.html' %}

{% block content %}

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card mb-4 box-shadow">
                        <img src="https://source.unsplash.com/random/800x600" alt="card image cap" class="card-img-top">
                        <div class="card-body">
                            <h4><a href="{{ core.get_absolute_urls }}">{{ post.title }}</a></h4>
                            <p class="card-text"></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a href="{{ post.get_absolute_urls }}" class="btn btn-sm btn-outline-primary" role="button" aria-pressed="true">View</a>
                                    <a href="{% url 'core:edit' post.pk %}" class="btn btn-sm btn-outline-primary" role="button" aria-pressed="true">Edit</a>
                                    <a href="{% url 'core:delete' post.pk %}" class="btn btn-sm btn-outline-primary" role="button" aria-pressed="true">Delete</a>
                                </div>
                                    
                                <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

coresite/core/templates/core/single.html
{% extends 'core/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12 pt-5">
            <img src="https://source.unsplash.com/random/1600x900" alt="" class="card-img-top">
            <h2 class="pt-5">{{ post.title}}</h2>
            <p>{{ post.excerpt }}</p>
        </div>
    </div>
</div>
{% endblock%}